//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InternetTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are available..
        /// </summary>
        public static string AvailableUpdates {
            get {
                return ResourceManager.GetString("AvailableUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change InternetTest theme..
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking updates on start is disabled..
        /// </summary>
        public static string CheckUpdatesDisabledOnStart {
            get {
                return ResourceManager.GetString("CheckUpdatesDisabledOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates on start.
        /// </summary>
        public static string CheckUpdatesOnStart {
            get {
                return ResourceManager.GetString("CheckUpdatesOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are connected to Internet.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default protocol..
        /// </summary>
        public static string DefaultProtocol {
            get {
                return ResourceManager.GetString("DefaultProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownDetector.
        /// </summary>
        public static string DownDetector {
            get {
                return ResourceManager.GetString("DownDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The history is empty..
        /// </summary>
        public static string EmptyHistory {
            get {
                return ResourceManager.GetString("EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a URL to get started.
        /// </summary>
        public static string EnterURLToCheck {
            get {
                return ResourceManager.GetString("EnterURLToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon.
        /// </summary>
        public static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening.
        /// </summary>
        public static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good night.
        /// </summary>
        public static string GoodNight {
            get {
                return ResourceManager.GetString("GoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Historic {
            get {
                return ResourceManager.GetString("Historic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        public static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP protocol.
        /// </summary>
        public static string HTTPProtocol {
            get {
                return ResourceManager.GetString("HTTPProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS.
        /// </summary>
        public static string HTTPS {
            get {
                return ResourceManager.GetString("HTTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To install updates, InternetTest needs to restarts. Do you want to continue?.
        /// </summary>
        public static string InstallConfirmMsg {
            get {
                return ResourceManager.GetString("InstallConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install version.
        /// </summary>
        public static string InstallVersion {
            get {
                return ResourceManager.GetString("InstallVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternetTest.
        /// </summary>
        public static string InternetTest {
            get {
                return ResourceManager.GetString("InternetTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IP isn&apos;t valid..
        /// </summary>
        public static string InvalidIP {
            get {
                return ResourceManager.GetString("InvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website URL is invalid..
        /// </summary>
        public static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISP.
        /// </summary>
        public static string ISP {
            get {
                return ResourceManager.GetString("ISP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch a test on start.
        /// </summary>
        public static string LaunchTestOnStart {
            get {
                return ResourceManager.GetString("LaunchTestOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch a test to check your connection.
        /// </summary>
        public static string LaunchTestToCheckConnection {
            get {
                return ResourceManager.GetString("LaunchTestToCheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localize IP.
        /// </summary>
        public static string LocalizeIP {
            get {
                return ResourceManager.GetString("LocalizeIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map provider.
        /// </summary>
        public static string MapProvider {
            get {
                return ResourceManager.GetString("MapProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map provider used to show an IP localization..
        /// </summary>
        public static string MapProviderDescription {
            get {
                return ResourceManager.GetString("MapProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My IP.
        /// </summary>
        public static string MyIP {
            get {
                return ResourceManager.GetString("MyIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternetTest needs to restart to apply the changes. Do you want to restart now?.
        /// </summary>
        public static string NeedRestartToApplyChanges {
            get {
                return ResourceManager.GetString("NeedRestartToApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t connected to Internet.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a notification when updates are available.
        /// </summary>
        public static string NotifyUpdates {
            get {
                return ResourceManager.GetString("NotifyUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On start.
        /// </summary>
        public static string OnStart {
            get {
                return ResourceManager.GetString("OnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open browser.
        /// </summary>
        public static string OpenBrowser {
            get {
                return ResourceManager.GetString("OpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in a browser.
        /// </summary>
        public static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on a map.
        /// </summary>
        public static string OpenMap {
            get {
                return ResourceManager.GetString("OpenMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all settings?.
        /// </summary>
        public static string ResetSettingsConfirmMsg {
            get {
                return ResourceManager.GetString("ResetSettingsConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See licenses.
        /// </summary>
        public static string SeeLicenses {
            get {
                return ResourceManager.GetString("SeeLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All settings have been reset, InternetTest will now restart..
        /// </summary>
        public static string SettingsReset {
            get {
                return ResourceManager.GetString("SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup page.
        /// </summary>
        public static string StartupPage {
            get {
                return ResourceManager.GetString("StartupPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test website.
        /// </summary>
        public static string TestSite {
            get {
                return ResourceManager.GetString("TestSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website where the connection is tested..
        /// </summary>
        public static string TestSiteDescription {
            get {
                return ResourceManager.GetString("TestSiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check updates.
        /// </summary>
        public static string UnableToCheckUpdates {
            get {
                return ResourceManager.GetString("UnableToCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternetTest is up to date..
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternetTest is using IP-API.com to get IPs&apos; informations..
        /// </summary>
        public static string WarningIPAPI {
            get {
                return ResourceManager.GetString("WarningIPAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website is up.
        /// </summary>
        public static string WebsiteAvailable {
            get {
                return ResourceManager.GetString("WebsiteAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website is down.
        /// </summary>
        public static string WebsiteDown {
            get {
                return ResourceManager.GetString("WebsiteDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Code.
        /// </summary>
        public static string ZIPCode {
            get {
                return ResourceManager.GetString("ZIPCode", resourceCulture);
            }
        }
    }
}
