version: 2
updates:
  - package-ecosystem: nuget
    directory: "/InternetTest"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    target-branch: vNext
    reviewers:
      - lpeyr
    assignees:
      - lpeyr
    ignore:
      - dependency-name: LeoCorpLibrary
        versions:
          - 3.3.0.2102
