name: Nightly Build
on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Install the .NET workload
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build App
        run: dotnet build InternetTest\InternetTest.sln -c Release -p:DefineConstants=NIGHTLY

      - name: Test App
        run: dotnet test InternetTest\InternetTest.sln

      - name: Build Setup
        uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with:
          filepath: "./InternetTest.Setup/Setup.iss"

      - name: Upload Setup file
        uses: actions/upload-artifact@v4
        with:
          name: InternetTestProSetup.exe
          path: "./InternetTest.Setup/Output/InternetTestProSetup.exe"
